//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Detecting_System.WS_Eqp_NIR_JM {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Eqp_NIRSoap", Namespace="http://tempuri.org/")]
    public partial class Eqp_NIR : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckInputTrayOperationCompleted;
        
        private System.Threading.SendOrPostCallback DoFinishOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Eqp_NIR() {
            this.Url = global::Detecting_System.Properties.Settings.Default.Detecting_System_WS_Eqp_NIR_JM_Eqp_NIR;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckInputTrayCompletedEventHandler CheckInputTrayCompleted;
        
        /// <remarks/>
        public event DoFinishCompletedEventHandler DoFinishCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckInputTray", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckInputTray(string sCoatingTrayNo, string sTestType, string sEqpNo, System.DateTime dtNow, out string sMsg) {
            object[] results = this.Invoke("CheckInputTray", new object[] {
                        sCoatingTrayNo,
                        sTestType,
                        sEqpNo,
                        dtNow});
            sMsg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckInputTrayAsync(string sCoatingTrayNo, string sTestType, string sEqpNo, System.DateTime dtNow) {
            this.CheckInputTrayAsync(sCoatingTrayNo, sTestType, sEqpNo, dtNow, null);
        }
        
        /// <remarks/>
        public void CheckInputTrayAsync(string sCoatingTrayNo, string sTestType, string sEqpNo, System.DateTime dtNow, object userState) {
            if ((this.CheckInputTrayOperationCompleted == null)) {
                this.CheckInputTrayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckInputTrayOperationCompleted);
            }
            this.InvokeAsync("CheckInputTray", new object[] {
                        sCoatingTrayNo,
                        sTestType,
                        sEqpNo,
                        dtNow}, this.CheckInputTrayOperationCompleted, userState);
        }
        
        private void OnCheckInputTrayOperationCompleted(object arg) {
            if ((this.CheckInputTrayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckInputTrayCompleted(this, new CheckInputTrayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DoFinish", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DoFinish(string sCoatingTrayNo, string sEqpNo, [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")] [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)] string[][] arrResult, System.DateTime dtNow, out string sMsg) {
            object[] results = this.Invoke("DoFinish", new object[] {
                        sCoatingTrayNo,
                        sEqpNo,
                        arrResult,
                        dtNow});
            sMsg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DoFinishAsync(string sCoatingTrayNo, string sEqpNo, string[][] arrResult, System.DateTime dtNow) {
            this.DoFinishAsync(sCoatingTrayNo, sEqpNo, arrResult, dtNow, null);
        }
        
        /// <remarks/>
        public void DoFinishAsync(string sCoatingTrayNo, string sEqpNo, string[][] arrResult, System.DateTime dtNow, object userState) {
            if ((this.DoFinishOperationCompleted == null)) {
                this.DoFinishOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoFinishOperationCompleted);
            }
            this.InvokeAsync("DoFinish", new object[] {
                        sCoatingTrayNo,
                        sEqpNo,
                        arrResult,
                        dtNow}, this.DoFinishOperationCompleted, userState);
        }
        
        private void OnDoFinishOperationCompleted(object arg) {
            if ((this.DoFinishCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoFinishCompleted(this, new DoFinishCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void CheckInputTrayCompletedEventHandler(object sender, CheckInputTrayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckInputTrayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckInputTrayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void DoFinishCompletedEventHandler(object sender, DoFinishCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoFinishCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DoFinishCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591